load_pages:
  name: Load pages.jsonl
  description: Clears plate and loads new layout from pages.jsonl file (or optional path)
  target:
  fields:
    path:
      name: Path
      description: Path to the file containing the plate layout in JSONL format
      required: true
      example: "/config/pages.jsonl"
      selector:
        text:

wakeup:
  name: Wakeup
  description: This is helpful e.g. when you want to wake up the display when an external event has occurred, like a PIR motion sensor.
  target:

next_page:
  name: Next Page
  description: Changes plate to the next page
  target:

prev_page:
  name: Previous Page
  description: Changes plate to the previous page
  target:

change_page:
  name: Change Page
  description: Changes plate to the provided page
  target:
  fields:
    page:
      name: Page
      description: Page number to change to
      required: true
      selector:
        number:
          min: 1
          max: 12